# Site settings
title: Tooploox &mdash; mobile apps development
email: hello@tooploox.com
description: > # this means to ignore newlines until "baseurl:"
     Clean and beautiful design, great user experience and simplicity is in our DNA.
     We work with plethora of technologies, most notably iOS, Android, Python and Node.js.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.tooploox.com" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
